### ISSUE TITLE
When using Hero Mancer for the second time in a session, ability score generation breaks

### ISSUE THREAD

**Issue by mohd2126** [Sayshal/hero-mancer#4]
![image](https://github.com/user-attachments/assets/4b706f24-ccee-4e52-9837-5b5f8ebd7c10)
![image](https://github.com/user-attachments/assets/b860febf-91af-4233-93eb-22dece223231)

**Comment by Sayshal** [comment]
This should be fixed [here](https://github.com/Sayshal/hero-mancer/commit/5b7bc3196e3c73eb0dc1f16c3ba528577589bfe3), just waiting for Github to release it. Let me know if it's fixed for you in 0.2.1 once it's published.
